### ISSUE TITLE
1.3.10 references the wrong docker registry in the imagestreams

### ISSUE THREAD

**Issue by rhuss** [syndesisio/fuse-online-install#20]
@paoloantinori https://github.com/syndesisio/fuse-ignite-install/blob/f8ff386855a490ed6cb4ab95752674646e010582/resources/fuse-ignite-image-streams.yml#L47 is the internal registry, isn't it ?

**Comment by paoloantinori** [comment]
Hi Roland, that's the one in use for current CR phase. In not expecting
that to be the one to be used for public GA, but test and validation for is
are happening on that one.

There is an externalised parameter for release.sh to provide it at release
time

On 17 May 2018 21:42, "Roland Huß" <notifications@github.com> wrote:

@paoloantinori <https://github.com/paoloantinori>
https://github.com/syndesisio/fuse-ignite-install/blob/f8ff386855a490ed6cb4ab95752674646e010582/resources/fuse-ignite-image-streams.yml#L47
is the internal registry, isn't it ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/fuse-ignite-install/issues/20>, or mute the
thread

**Comment by rhuss** [comment]
@paoloantinori ok, let me create a 1.3.10-CR tag with refering to the internal registry and repository. 

Wdyt about moving on to 1.4.0 for GA ?

**Comment by dsimansk** [comment]
It might be problematic as we need to update the reference in documentatio,
that is pointing to the scripts, currently 1.3. I'm not sure if there is
enough time to rollout doc update also. Anyway we have 1.3 in maven version
also.
