### ISSUE TITLE
Consider use of floating tag reference in ImageStream

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/fuse-online-install#23]
We currently have specific reference to patch(build) level of Docker image from RH registry. Therefor when new image is published due to update in underlayers, e.g. RHEL or OpenJDK we can't point users to do `oc import-image fuse-ignite-server:1.3`. But the whole image Docker image reference needs to be replaced. Probably the most smooth way is something like `oc replace -f updated-is.yml`.

There's another way to:
- remove `scheduled: true` - to prevent periodical pulls on floating tag
- reference Docker image with floating tag `1.0`
  - e.g. `registry.access.redhat.com/fuse7/fuse-ignite-ui:1.0`

When created new from scarth the images are imported for the first time. Then on image update release to pick it up only `oc import-image {isName}:{istag}` is required. This is outside of whole upgrade flow, when only images itself are changing.

https://github.com/syndesisio/fuse-ignite-install/blob/c6fb91dc982042635f381c6028c7e828e01db7dd/templates/fuse-ignite-image-streams.yml#L3-L18

Cc @rhuss @paoloantinori

**Comment by rhuss** [comment]
Sounds good to me, but we should test this somehow. IIUR the floating tag is automatically created by the brew build, right ?

**Comment by dsimansk** [comment]
Yes, and updated upon release to public registry.

**Comment by dsimansk** [comment]
@rhuss @paoloantinori hi guys, I'd like to sort this one out. There's another CVE update coming. Therefor we will have to finally update the image tags. Imho switching to `1.0` is much better alternartive. As there's no further maintenance needed in case of CVEs/image updates.

**Comment by heiko-braun** [comment]
@rhuss I think this can be closed?

**Comment by rhuss** [comment]
Actually, I think its still a very valid idea when doing respins because of base image fixes (like for CVEs in Java). However, I don't know whether productisation maintains a floating tag on the latest production builds (like for 1.1 pointing to 1.1_5 when 1.1_5 is the latest build number).

But I think our current solution with having a floating images-stream tag (instead of a floating docker image tag as referred to in this call) is not so bad either (one would need to create a new ImageStreamTag for a new respin), so I think we can close this for now.
