### ISSUE TITLE
Online registration app misses parameter SAR_PROJECT

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/fuse-online-install#61]
Apparently the provisioning app doesn't use the SAR_PROJECT parameter yet:

```
error: error processing template "fuse-ignite/fuse-ignite-1.5": Template.template.openshift.io "fuse-ignite-1.5" is invalid: template.parameters[4]: Required value: template.parameters[4]: parameter SAR_PROJECT is required and must be      
```

It has been added in 7.2.

See also https://github.com/syndesisio/syndesis/issues/3687

**Comment by heiko-braun** [comment]
@rhuss I guess this code requires changes to support SAR_PARAMETER:

https://github.com/gashcrumb/online-registration/blob/f2af131a82078f8b828cf5143bcea9a1138d4594/app/models/master_plans/fuse_ignite.rb#L187

**Comment by rhuss** [comment]
that might be a point, but as we actually extract the template from the operator image (which has that parameter and also the upgrade persistent volume), removing this part is a manual step after release.sh is called ? If this is a permanent thing we should add this kind of removal as part of release.sh so that it gets removed automatically.

Should I add this to the script (i.e. this post-mangling of the release template as it is in the fuse-online-operator image), only for OSO ? Or should I create a separate template for OSO ? Not sure why we can't update the template instantiation step in OSO. Really not sure what the status of the OSO installation procedure is (e.g. do we already have the additional PVC for the upgrade volume ?)

**Comment by heiko-braun** [comment]
> Not sure why we can't update the template instantiation step in OSO. 

Nobody said that. Why do you assume we cannot change it? The motivation for creating the ticket was to actually make the changes ...

**Comment by heiko-braun** [comment]
> do we already have the additional PVC for the upgrade volume  

yes, these changes should be in place

**Comment by heiko-braun** [comment]
I've created a PR, but need @rhuss to verify the changes:

https://github.com/openshift/online-registration/pull/1409
