### ISSUE TITLE
bash update_ocp.sh --version not working

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/fuse-online-install#66]
@tmielke commented on [Thu Dec 13 2018](https://github.com/syndesisio/syndesis/issues/4227)

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Following the [10.6. Upgrade Fuse Online on OCP](https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/integrating_applications_with_fuse_online/how-to-install-on-ocp_ug#upgrade-on-ocp_ocp) documentation 

in step 4 I am told to run
<code>
$ bash update_ocp.sh --version
</code>
but the script fails with 
<code>
update_ocp.sh: line 385: /Users/tmielke/Downloads/fuse_online_config.sh: No such file or directory
</code>

**Comment by heiko-braun** [comment]
@rhuss Looks like a quick fix, is it?

**Comment by tmielke** [comment]
I am not sure where the missing file is supposed to come from as per instructions I only downloaded 
wget https://raw.githubusercontent.com/syndesisio/fuse-online-install/1.5/update_ocp.sh

**Comment by rhuss** [comment]
Actually, this is misunderstanding between me and docs. Actually my initial input was to download the full release from https://github.com/syndesisio/fuse-online-install/archive/1.5.tar.gz, uncompress and run update_ocp.sh from there (as it includes the version).

My suggestion was to adopt the release process to embed the data in the `fuse_online_config.sh` file directly in update_ocp.sh so that it becomes standalone again, but I'm not sure whether we agreed on this for this release or for 7.3.

For 7.2. I think it's easier to adapt the documentation again (@fbolton should have the original instructions that I've sent) and add the embed fix for 7.3

Sorry for the confusion.

**Comment by rhuss** [comment]
The issue that we opened for this is #63

**Comment by rhuss** [comment]
@TovaCohen is working on a documentation update, so lets close this issue and fix it with #63
